/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'responded' : boolean,
  'listingId' : bigint,
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'senderName' : string,
}
export type Currency = { 'nativeCurrency' : null } |
  { 'rupees' : null };
export type ExternalBlob = Uint8Array;
export interface Listing {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'modifiedTimestamp' : Time,
  'description' : string,
  'seller' : Principal,
  'listingType' : string,
  'currency' : Currency,
  'createdTimestamp' : Time,
  'category' : PropertyCategory,
  'quotedPrice' : bigint,
  'location' : string,
  'images' : Array<ExternalBlob>,
}
export type ListingStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'sold' : null } |
  { 'archived' : null };
export type PropertyCategory = { 'commercial' : null } |
  { 'land' : null } |
  { 'newDevelopment' : null } |
  { 'residential' : null } |
  { 'agriculture' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, PropertyCategory, string, bigint, Currency, string],
    bigint
  >,
  'fetchRandomListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], Listing>,
  'getListingsBySeller' : ActorMethod<[Principal], Array<Listing>>,
  'getMessagesForListing' : ActorMethod<[bigint], Array<ContactMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageResponded' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[bigint, string, string], bigint>,
  'submitOffer' : ActorMethod<[bigint, bigint, Currency, string], bigint>,
  'updateListing' : ActorMethod<
    [
      bigint,
      string,
      string,
      PropertyCategory,
      string,
      bigint,
      Currency,
      string,
      ListingStatus,
    ],
    undefined
  >,
  'updateOfferStatus' : ActorMethod<[bigint, boolean, boolean], undefined>,
  'uploadListingImages' : ActorMethod<[bigint, Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];